import PDFDocument from 'pdfkit';
import ExcelJS from 'exceljs';
import prisma from '../config/database';
import { daysUntilExpiry, formatDate } from '../utils/helpers';
import { PassThrough } from 'stream';
import path from 'path';
import fs from 'fs';

export class ReportService {
  /**
   * Generate expiry report as PDF
   */
  async generateExpiryReportPDF(): Promise<Buffer> {
    const chemicals = await prisma.chemical.findMany({
      orderBy: { expiryDate: 'asc' },
      include: {
        addedBy: { select: { firstName: true, lastName: true } },
      },
    });

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: 'A4' });
      const buffers: Buffer[] = [];

      doc.on('data', (chunk) => buffers.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(buffers)));
      doc.on('error', reject);
      // Header Logo
      try {
        let logoPath = path.join(__dirname, '../assets/logo.png');
        if (!fs.existsSync(logoPath)) {
          logoPath = path.join(process.cwd(), 'src/assets/logo.png');
        }
        if (!fs.existsSync(logoPath)) {
          logoPath = path.join(process.cwd(), 'backend/src/assets/logo.png');
        }
        doc.image(logoPath, 222, 30, { width: 150 });
        doc.moveDown(3);
      } catch (err) {
        doc.fontSize(22).fillColor('#801818').text('AmSpec', { align: 'center' });
        doc.moveDown(0.5);
      }
      doc.fontSize(16).fillColor('#8A1C14').text('Chemical Expiry Report', { align: 'center' });
      doc.fontSize(10).fillColor('#64748b').text(`Generated: ${formatDate(new Date())}`, { align: 'center' });
      doc.moveDown(2);

      // Summary
      const expired = chemicals.filter(c => c.status === 'EXPIRED').length;
      const nearExpiry = chemicals.filter(c => c.status === 'NEAR_EXPIRY').length;
      const safe = chemicals.filter(c => c.status === 'SAFE').length;

      doc.fontSize(12).fillColor('#0f172a').text('Summary', { underline: true });
      doc.fontSize(10).fillColor('#334155');
      doc.text(`Total Chemicals: ${chemicals.length}`);
      doc.text(`Expired: ${expired}`, { continued: false });
      doc.text(`Near Expiry (≤30 days): ${nearExpiry}`);
      doc.text(`Safe: ${safe}`);
      doc.moveDown();

      // Table header
      const startX = 50;
      let y = doc.y;
      const colWidths = [140, 80, 80, 60, 70, 65];
      const headers = ['Chemical Name', 'Batch No.', 'Expiry Date', 'Status', 'Quantity', 'Days Left'];

      doc.fontSize(9).fillColor('#ffffff');
      doc.rect(startX, y, 495, 20).fill('#0f172a');
      headers.forEach((header, i) => {
        const x = startX + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
        doc.fillColor('#ffffff').text(header, x + 4, y + 5, { width: colWidths[i] - 8 });
      });
      y += 20;

      // Table rows
      chemicals.forEach((chem, index) => {
        if (y > 750) {
          doc.addPage();
          y = 50;
        }

        const bgColor = index % 2 === 0 ? '#f8fafc' : '#ffffff';
        doc.rect(startX, y, 495, 18).fill(bgColor);

        const days = daysUntilExpiry(chem.expiryDate);
        const statusColor = chem.status === 'EXPIRED' ? '#ef4444' : chem.status === 'NEAR_EXPIRY' ? '#f59e0b' : '#22c55e';

        const values = [
          chem.name.substring(0, 25),
          chem.batchNumber || 'N/A',
          formatDate(chem.expiryDate),
          chem.status,
          `${chem.quantity} ${chem.unit}`,
          days <= 0 ? 'Expired' : `${days}d`,
        ];

        values.forEach((val, i) => {
          const x = startX + colWidths.slice(0, i).reduce((a, b) => a + b, 0);
          const color = i === 3 || i === 5 ? statusColor : '#334155';
          doc.fontSize(8).fillColor(color).text(val, x + 4, y + 4, { width: colWidths[i] - 8 });
        });

        y += 18;
      });

      // Footer
      doc.moveDown(2);
      doc.fontSize(8).fillColor('#94a3b8').text(
        'This report was automatically generated by the AmSpec Lab Inventory Management System.',
        { align: 'center' }
      );

      doc.end();
    });
  }

  /**
   * Generate inventory report as Excel
   */
  async generateInventoryExcel(): Promise<Buffer> {
    const chemicals = await prisma.chemical.findMany({
      orderBy: { name: 'asc' },
      include: {
        addedBy: { select: { firstName: true, lastName: true } },
      },
    });

    const workbook = new ExcelJS.Workbook();
    workbook.creator = 'AmSpec System';
    workbook.created = new Date();

    // Inventory Sheet
    const sheet = workbook.addWorksheet('Chemical Inventory', {
      headerFooter: {
        firstHeader: 'AmSpec Chemical Inventory Report',
      },
    });

    sheet.columns = [
      { header: 'Chemical Name', key: 'name', width: 25 },
      { header: 'CAS Number', key: 'casNumber', width: 15 },
      { header: 'Batch Number', key: 'batchNumber', width: 15 },
      { header: 'Manufacturer', key: 'manufacturer', width: 20 },
      { header: 'Quantity', key: 'quantity', width: 10 },
      { header: 'Unit', key: 'unit', width: 8 },
      { header: 'Purchase Date', key: 'purchaseDate', width: 14 },
      { header: 'Expiry Date', key: 'expiryDate', width: 14 },
      { header: 'Status', key: 'status', width: 12 },
      { header: 'Days Left', key: 'daysLeft', width: 10 },
      { header: 'Hazard Class', key: 'hazardClass', width: 18 },
      { header: 'Storage Location', key: 'storageLocation', width: 18 },
      { header: 'Supplier', key: 'supplierName', width: 20 },
      { header: 'Added By', key: 'addedBy', width: 18 },
    ];

    // Style header row
    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF0F172A' },
    };

    // Add data rows
    chemicals.forEach(chem => {
      const days = daysUntilExpiry(chem.expiryDate);
      const row = sheet.addRow({
        name: chem.name,
        casNumber: chem.casNumber || 'N/A',
        batchNumber: chem.batchNumber || 'N/A',
        manufacturer: chem.manufacturer || 'N/A',
        quantity: chem.quantity,
        unit: chem.unit,
        purchaseDate: formatDate(chem.purchaseDate),
        expiryDate: formatDate(chem.expiryDate),
        status: chem.status,
        daysLeft: days <= 0 ? 'Expired' : days,
        hazardClass: chem.hazardClass,
        storageLocation: chem.storageLocation || 'N/A',
        supplierName: chem.supplierName || 'N/A',
        addedBy: `${chem.addedBy.firstName} ${chem.addedBy.lastName}`,
      });

      // Color-code status
      const statusCell = row.getCell('status');
      if (chem.status === 'EXPIRED') {
        statusCell.font = { color: { argb: 'FFEF4444' }, bold: true };
      } else if (chem.status === 'NEAR_EXPIRY') {
        statusCell.font = { color: { argb: 'FFF59E0B' }, bold: true };
      } else {
        statusCell.font = { color: { argb: 'FF22C55E' }, bold: true };
      }
    });

    // Auto-filter
    sheet.autoFilter = {
      from: 'A1',
      to: `N${chemicals.length + 1}`,
    };

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }

  /**
   * Generate audit log report as Excel
   */
  async generateAuditExcel(startDate?: Date, endDate?: Date): Promise<Buffer> {
    const where: any = {};
    if (startDate) where.createdAt = { gte: startDate };
    if (endDate) where.createdAt = { ...where.createdAt, lte: endDate };

    const logs = await prisma.auditLog.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: 1000,
      include: {
        user: { select: { firstName: true, lastName: true, email: true } },
      },
    });

    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Audit Log');

    sheet.columns = [
      { header: 'Timestamp', key: 'timestamp', width: 22 },
      { header: 'User', key: 'user', width: 20 },
      { header: 'Email', key: 'email', width: 25 },
      { header: 'Action', key: 'action', width: 15 },
      { header: 'Entity Type', key: 'entityType', width: 15 },
      { header: 'Entity ID', key: 'entityId', width: 38 },
      { header: 'IP Address', key: 'ipAddress', width: 15 },
    ];

    const headerRow = sheet.getRow(1);
    headerRow.font = { bold: true, color: { argb: 'FFFFFFFF' } };
    headerRow.fill = {
      type: 'pattern',
      pattern: 'solid',
      fgColor: { argb: 'FF0F172A' },
    };

    logs.forEach(log => {
      sheet.addRow({
        timestamp: log.createdAt.toISOString(),
        user: `${log.user.firstName} ${log.user.lastName}`,
        email: log.user.email,
        action: log.action,
        entityType: log.entityType,
        entityId: log.entityId || 'N/A',
        ipAddress: log.ipAddress || 'N/A',
      });
    });

    const buffer = await workbook.xlsx.writeBuffer();
    return Buffer.from(buffer);
  }
}

export default new ReportService();
